package ar.com.mariano.tpi.enumerators;

public enum Provincias {
	
	BUENOS_AIRES, CATAMARCA, CHACO, CHUBUT, CÓRDOBA, CORRIENTES, ENTRE_RÍOS, FORMOSA, JUJUY, 
	LA_PAMPA, LA_RIOJA, MENDOZA, MISIONES, NEUQUÉN, RÍO_NEGRO, SALTA, SAN_JUAN, SAN_LUIS, 
	SANTA_CRUZ, SANTA_FE, SANTIAGO_DEL_ESTERO, TIERRA_DEL_FUEGO_ANTÁRTIDA_E_ISLAS_DEL_ATLÁNTICO_SUR, TUCUMÁN

}
